apiVersion: batch/v1
kind: CronJob
metadata:
  name: cart-cleanup
  namespace: {{ .Values.namespace }}
spec:
  schedule: "{{ .Values.schedule }}"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cart-cleanup
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              args: ["--spring.profiles.active=cleanup"]
              env:
                - name: SPRING_CART_SERVER_PORT
                  value: "13000"
                - name: SPRING_DATASOURCE_URL
                  value: {{ .Values.spring.datasource.url | quote }}
                - name: SPRING_DATASOURCE_USERNAME
                  value: {{ .Values.spring.datasource.username | quote }}
                - name: SPRING_DATASOURCE_PASSWORD
                  value: {{ .Values.spring.datasource.password | quote }}
                - name: SPRING_KEYCLOAK_URL
                  value: {{ .Values.spring.keycloak.url | quote }}
              resources:                         # ✅ 여기에 위치해야 함!
                {{- toYaml .Values.resources | nindent 16 }}
          restartPolicy: OnFailure

