app:
  namespace: order-service
  name: order-service-api
  replicas: 1
  image: '430118853107.dkr.ecr.ap-northeast-2.amazonaws.com/order-service:e4543425882f094f12bf37590bda838297cba5a0'
  port: 11000 # 퍄드(컨테이너화된 애플리케이션) 서비스 포트
  resources: {}
podLabels:
  tier: backend
probes:
  readiness: {}
  liveness: {}
service:
  enabled: true
  type: ClusterIP
  port: 80
ingress:
  enabled: false
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://mysql.inkcloud.svc.cluster.local:3306/order_db?serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: root
    password: "1234"
env:
  SPRING_KEYCLOAK_URL: https://keycloak.inkcloud.click
  SPRING_KAFKA: kafka-cluster-dev-broker.broker.svc.cluster.local:9092
  SPRING_API_GATEWAY_CORS: http://api-gateway-service.inkcloud.svc.cluster.local:25000
