apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  namespace: {{ .Values.app.namespace }}
data:
  SPRING_PRODUCT_SERVER_PORT: {{ .Values.app.port | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.spring.profiles.active | quote }}
  SPRING_PRODUCT_DATASOURCE_URL: {{ .Values.spring.datasource.url | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.spring.datasource.username | quote }}
  # PRODUCT_SERVICE_API_URL: {{ .Values.app.product_service_api_url | quote }}
  SPRING_KEYCLOAK_URL: {{ .Values.env.SPRING_KEYCLOAK_URL | quote }}
  SPRING_KAFKA: {{ .Values.env.SPRING_KAFKA | quote }}
  AWS_S3_BUCKET: {{ .Values.env.AWS_S3_BUCKET | quote }}
