apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      # Spring Cloud API Gateway(Spring Cloud Kubernetes)가 Kubernetes API 서버를 통해 Service 목록, Endpoints 등을 검색하려면,
      # Pod가 사용하는 ServiceAccount가 있어야 하고, 그 SA가 적절한 RBAC 권한을 갖고 있어야 합니다.
      # 따라서 다음 설정은 Deployment에 반드시 포함해야 합니다:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image }}
          ports:
            - containerPort: {{ .Values.app.port }}             
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: SERVER_PORT
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-secret
                  key: SPRING_DATASOURCE_PASSWORD

            # mysql 서비스에 설정된 Secret 설정 정보 참조
            # - name: SPRING_DATASOURCE_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: mysql-secret
            #       key: MYSQL_ROOT_PASSWORD
            - name: SPRING_KEYCLOAK_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: SPRING_KEYCLOAK_URL
            
            - name: SPRING_KAFKA
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: SPRING_KAFKA

            - name: AWS_S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.name }}-config
                  key: AWS_S3_BUCKET


          {{- with .Values.app.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.probes.readiness }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.probes.liveness }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

