apiVersion: v1
kind: Service
metadata:
  name: broker
  labels:
    {{- include "kafka-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  type: {{ .Values.kafka.service.type }}
  ports:
  - port: {{ .Values.kafka.service.port }}
    targetPort: external
    protocol: TCP
    name: external
  - port: {{ .Values.kafka.service.internalPort }}
    targetPort: internal
    protocol: TCP
    name: internal
  selector:
    {{- include "kafka-cluster.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka