apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-cluster.fullname" . }}-zookeeper
  labels:
    {{- include "kafka-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
spec:
  type: {{ .Values.zookeeper.service.type }}
  ports:
  - port: {{ .Values.zookeeper.service.port }}
    targetPort: client
    protocol: TCP
    name: client
  selector:
    {{- include "kafka-cluster.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
