apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka-cluster.fullname" . }}-zookeeper
  labels:
    {{- include "kafka-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kafka-cluster.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: zookeeper
  template:
    metadata:
      labels:
        {{- include "kafka-cluster.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: "{{ .Values.zookeeper.image.repository }}:{{ .Values.zookeeper.image.tag }}"
        imagePullPolicy: {{ .Values.zookeeper.image.pullPolicy }}
        ports:
        - containerPort: 2181
          name: client
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "{{ .Values.zookeeper.env.clientPort }}"
        - name: ZOOKEEPER_TICK_TIME
          value: "{{ .Values.zookeeper.env.tickTime }}"
        resources:
          {{- toYaml .Values.zookeeper.resources | nindent 10 }}