apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  namespace: {{ .Values.app.namespace }}
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.spring.datasource.password | b64enc | quote }}  # 64Base 인코딩
  SPRING_WEBHOOK_SECRET: {{ .Values.env.SPRING_WEBHOOK_SECRET | b64enc | quote }}  # 64Base 인코딩
  SPRING_PORTONE_SECRET: {{ .Values.env.SPRING_PORTONE_SECRET | b64enc | quote }}  # 64Base 인코딩
  SPRING_STORE_ID: {{ .Values.env.SPRING_STORE_ID | b64enc | quote }}  # 64Base 인코딩
  
