---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alert-secret
  namespace: alert-service
spec:
  encryptedData:
    SPRING_MAIL_PASSWORD: AgCc5w2bKoc7FlqdJqHMDoZcwsBlxbiSkj0KWE+SfwZkRM0NygCmQB7YVNNaxSGyY+w5QqptqwpNYypmgBrTeCMJ046Uq0LSizJmgg8EDg+4WIydwJwWqAPnZrbeDrYbeC56Dje000+X555QQBCRj8HbQNCZ38fRqbmehe67t5aUL+rcPqxW3EgXHKA4yhTlvKw6U/HjWof0LY5V7C/lWhGi7iXBhptqW6IvaIKSOZinK3PE59ym0A9IPeK+SV/CfWJexa4Q3hebAC7NqWclRDNtU9uwPqt/5puTBjWlSWSELbkdH12rUWiaX+vbBfuPEaLF7yjfPHox0qax7wy3anmK8NcgZYBU+mxCf9kDUhM++7s+gkWQTcdkK7leXXOCXFI6F/nskxGDEz0mx7E9qmMxqSyM/jSCVwqTUdSPonvqBuYloPx8KS4ejRGiWcfSklD1l0Jk/IDDUgXHeEt61o5lJZsSBVx9GYHZGUmVuzF93DDg0J0RDZBv+AFW36WjayWS4OFXP7YxebXFkI9qMOzeTcBUb8RyBD+759sLW//T0eGOSD2mJ+sTKOgeVOQYh0wGrQdIPfCeEW3tNbQcuTPZV82cYLD3pbzAKThMAdL80MNS+pCScNgSGIAzr6LIXL2QPTjqcVKvcBSv5f1/3OW5qA1EFIqE1aQphUZaa52TelX8d6k61KA4gI9w6ee4vTDBL+K/QbgKCNxOclTvyCZ3
  template:
    metadata:
      creationTimestamp: null
      name: alert-secret
      namespace: alert-service
    type: Opaque
