---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alert-secret
  namespace: alert-service
spec:
  encryptedData:
    SPRING_MAIL_PASSWORD: AgAFkfZFm2AKtiSC1ocq7k7t3DYsM3qMhydRgoEUBOVt4XbbzrPRMqLRsjsXKI/TX3MYMbi+67E6fBAeVHMgjpLph4DO7r4eXTuCzjJ5phswF2A9DhubSxW9z85k6nUra7U9tnEaDGrqPYBpZTGLJbWO4BZOBdbfMYs2ZfsScm9cwh5CyHZ5I+tOUcI1IHFisZkhfircUl1/VHy5LUXpiuEwVsSzPG9GXvP4dTL0Qlh7porP1jU7BLpEyMa8UXRGr5ZlezGK+S2Af08EcXze8NFwM6WWlPcUuJYF5pZ7pv85HAFxSdpkej7f8DAgnL1o1CmNa+6deBmEB0RqV+8EwrtbHMqVtGFcvbrY8penJIlYXnLTddJEuuR2MI0c3agtrXZIDTAtVV/vW21VvZDs1d8RrnXLQ3tFnBJek7xawwgIvAs/qO2fXYXui+mRJNN9YhT3R56c8DwJmhHSWUJJIMhm94LLIi0y+bGj9425dV0RYa7x9IQutw7r7a67NpBsg8FSGBpBbvhFwG2a4eESeknXU4ZBwXm7vSyWn/rbVwq2mJ5y+kueev9R6+MhqDlphvFUquNdYaVvRQIA7mMEkswD6bIVWjj8QTOawjOmZH/xOg8S8aqUqUpQm9Yw+DVUQ6TZHEKpoL6oFU7krQDUvXBPEiCXalHJw5YGJHnQ6Yrz2ke8OLA3JJjDr7YD+TotrpXNT1gyry/U2DMUbsI=
  template:
    metadata:
      creationTimestamp: null
      name: alert-secret
      namespace: alert-service
    type: Opaque
