---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alert-secret
  namespace: alert-service
spec:
  encryptedData:
    SPRING_MAIL_PASSWORD: AgBFOYSKPJKj9eATn/6OmMlUkyXyHSiG83AqMMiL83o55yhkU3NKpMMyFcnd8Et7c4Bhp7uOkJeGOv4JttBbL0RJ3LxBTiUCQF8TV06PSNxazd3EBzoxaMTzgsH4mv5PaZiyLwo7GQwq/pnU8M+G9+F1p8ubNd/uihSx4xMDsmh2ijRXv8XZB27PZzsuoz0CrogWT9ub48YFP1enoziQereIyQ6qZ1ohADKUlUAXxOGIE7ntsnPW2j0C2v6P+BJuuOVzi5bzR0SDeheN+2KF3aeWyemJoCoKL0CEO9/FXja18d/IUqRmJwVXw7ZlX0yPCWuADrnz04CLzNoUfSTEI1Bk5Jz4VV8oIw6oEY7I6pXnv6YXhLrfhdkkW1V3/B5lzaaHRvQU20B7glMMK/Mg73WnTFpcbZqzGRz8435lleWqf0zBTMdwHC/NA5tSXTogJV+jRPXoi3adnDdSJuwVp+pOcFNIV9ktIcl8xrNL2PwP8xStIe91TmzMLlVE2E2empkwDAIVsGErVchdHABj0qkcqwn8eSqmOF+Qxh+i7r03KGE5vvMQcFjwJvvQTX1hsgLufdqgvDvmxyzXi18gsEN68SP2NTnW2Wi2KAtNE/tWEzTmpKoA1aDpDE7UdbzmW2ILXJ90I3AsqvyrgvC/GmvM+s47onoWFMQTT9DQOqY7Cm89C2wua0U0u9o5a1lBbZpfmBcH4hazjjL+Mf1YN1td
  template:
    metadata:
      creationTimestamp: null
      name: alert-secret
      namespace: alert-service
    type: Opaque
