---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alert-secret
  namespace: alert-service
spec:
  encryptedData:
    SPRING_MAIL_PASSWORD: AgAV7tPXcydeR1d5XC0LgwQy1CatQb7BhqaTa53kkgc5o/8pYEapdpVkHyePB1p1WCIldg+EVDpwkZ3KA/ClniDSYKmfzikmAbmjD+VVMnVugWgI3BnGcPV9aohmouYp0QNIuJJ2PL8XoRyx2MG7UwZTMyS6eoqzGSx1m36tQ3m9GYu8Ceg0Wqgw2asnywtteQVR7bWAOc1GIxBLYnq4S9G16nG8HsBrf4zTUxu9Br0vfklZ6aOgQ00E4HL51b+E0GY5O9jqZMTKv4m49ZIUnMwjA9xoKV1JcdYr0SWy5VtUBhnbfYF4W6DpHXB1sn1tluLDzdwkhhW6jMow2HP/lxVxBi0s3YQkxW6T/4bLDRuATgH/kGdqKumZlNVNz3l5XReVcX2yryzhqbYhlUXT4xYTjt4l24WsuY06DvwFp+1NF4j6dIzHXlK2vB58+4RbVi261wuOcOsnXBGUILoE1+b6q4DYkQjAFfeRBycHU4P1xOKWK32hA4SwK/ycWriyDBuLy9t1tjgcquECXqkekNFO4YSkCz4CJcW5+LaD6EM33qyqTaCvr//9QJ2S4VXnxI8v2cNrzHmqdAVBPxWmOPo/i5Fd/JktC3ZHSV3IYvfS6pvgkIlg2xek9CsgUaveFLP1qysx6tJySHohdRVxRq+E2PlzBONmMl3KrYuid/mO94NCs87hNCtQ/AY2aBqkwwXgAxU2dR2BBgjPhBXC2/Bt
  template:
    metadata:
      creationTimestamp: null
      name: alert-secret
      namespace: alert-service
    type: Opaque
