apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  namespace: {{ .Values.app.namespace }}
data:
  SERVER_PORT: {{ .Values.app.port | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.spring.profiles.active | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.spring.datasource.url | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.spring.datasource.username | quote }}
  SPRING_KEYCLOAK_URL: {{ .Values.env.SPRING_KEYCLOAK_URL | quote }}
  SPRING_KAFKA: {{ .Values.env.SPRING_KAFKA | quote }}