apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-env
  namespace: {{ .Values.app.namespace }}
data:
  REACT_APP_KEYCLOAK_TOKEN_URL: {{ .Values.env.REACT_APP_KEYCLOAK_TOKEN_URL | quote }}
  REACT_APP_KEYCLOAK_CLIENT_ID: {{ .Values.env.REACT_APP_KEYCLOAK_CLIENT_ID | quote }}
  REACT_APP_KEYCLOAK_CLIENT_SECRET: {{ .Values.env.REACT_APP_KEYCLOAK_CLIENT_SECRET | quote }}
  REACT_APP_V2_API_SECRET: {{ .Values.env.REACT_APP_V2_API_SECRET | quote }}
  REACT_APP_V2_WEBHOOK_SECRET: {{ .Values.env.REACT_APP_V2_WEBHOOK_SECRET | quote }}
  REACT_APP_STORE_ID: {{ .Values.env.REACT_APP_STORE_ID | quote }}
  REACT_APP_CHANNEL_ID: {{ .Values.env.REACT_APP_CHANNEL_ID | quote }}
  REACT_APP_PREFIX_URL: {{ .Values.env.REACT_APP_PREFIX_URL | quote }}