env:
  - name: REACT_APP_KEYCLOAK_TOKEN_URL
    valueFrom:
      configMapKeyRef:
        name: {{ .Values.app.name }}-env
        key: REACT_APP_KEYCLOAK_TOKEN_URL
  - name: REACT_APP_KEYCLOAK_CLIENT_ID
    valueFrom:
      configMapKeyRef:
        name: {{ .Values.app.name }}-env
        key: REACT_APP_KEYCLOAK_CLIENT_ID
  - name: REACT_APP_KEYCLOAK_CLIENT_SECRET
    valueFrom:
      configMapKeyRef:
        name: {{ .Values.app.name }}-env
        key: REACT_APP_KEYCLOAK_CLIENT_SECRET
  - name: REACT_APP_V2_API_SECRET
    valueFrom:
      configMapKeyRef:
        name: {{ .Values.app.name }}-env
        key: REACT_APP_V2_API_SECRET
  - name: REACT_APP_V2_WEBHOOK_SECRET
    valueFrom:
      configMapKeyRef:
        name: {{ .Values.app.name }}-env
        key: REACT_APP_V2_WEBHOOK_SECRET
  - name: REACT_APP_STORE_ID
    valueFrom:
      configMapKeyRef:
        name: {{ .Values.app.name }}-env
        key: REACT_APP_STORE_ID
  - name: REACT_APP_CHANNEL_ID
    valueFrom:
      configMapKeyRef:
        name: {{ .Values.app.name }}-env
        key: REACT_APP_CHANNEL_ID
  - name: REACT_APP_PREFIX_URL
    valueFrom:
      configMapKeyRef:
        name: {{ .Values.app.name }}-env
        key: REACT_APP_PREFIX_URL