app:
  namespace: inkcloud-front
  name: inkcloud-front
  replicas: 1
  image: '430118853107.dkr.ecr.ap-northeast-2.amazonaws.com/inkcloud-front:5ae1368e54cca3bd3a114b2fade773e40b21161f'
env:
  REACT_APP_KEYCLOAK_TOKEN_URL: https://keycloak.inkcloud.click/realms/inkcloud/protocol/openid-connect/token
  REACT_APP_KEYCLOAK_CLIENT_ID: react-app
  REACT_APP_STORE_ID: store-c2066836-39bc-4ccd-8cd1-37501975c002
  REACT_APP_CHANNEL_ID: channel-key-bdc01ed7-11ea-4249-b830-75f9ee3d5580
  REACT_APP_PREFIX_URL: /api/v1
ingress:
  enabled: true
  host: www.inkcloud.click
  path: /
  pathType: Prefix
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # 필요시 cert-manager 등 추가
service:
  type: ClusterIP
  port: 80
  targetPort: 80
