app:
  namespace: inkcloud-front
  name: inkcloud-front
  replicas: 1
  image: '430118853107.dkr.ecr.ap-northeast-2.amazonaws.com/inkcloud-front:7374454d91a5325c3ae9692eb184377ab5eab5b7'
env:
  REACT_APP_KEYCLOAK_TOKEN_URL: http://localhost:8080/realms/inkcloud/protocol/openid-connect/token
  REACT_APP_KEYCLOAK_CLIENT_ID: react-app
  REACT_APP_KEYCLOAK_CLIENT_SECRET: 0gjjZ04hnduiaeDhLD36jvgEFKkDoGLT
  REACT_APP_V2_API_SECRET: TFwxYs4OeqxDTohsJzFYM3duxk7ZCjH2TxBCy6fS1UhmvgBxhksfKDi677P26PDCZMbtA9aadEQJ83Q3
  REACT_APP_V2_WEBHOOK_SECRET: whsec_eHbQOBcyaLiczfx7exstiy9GtdkM9Z/gT/3p0I9yhgs=
  REACT_APP_STORE_ID: store-a4a84348-266c-4b8a-9c92-97021a22d621
  REACT_APP_CHANNEL_ID: channel-key-ed57122d-6577-4a17-aca2-52f431c26705
  REACT_APP_PREFIX_URL: /api/v1
ingress:
  enabled: true
  host: www.inkcloud.click
  path: /
  pathType: Prefix
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # 필요시 cert-manager 등 추가
service:
  type: ClusterIP
  port: 80
  targetPort: 80
