apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  namespace: {{ .Values.app.namespace }}
data:
  SPRING_BESTSELLERS_SERVER_PORT: {{ .Values.app.port | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.spring.profiles.active | quote }}
  SPRING_KEYCLOAK_URL: {{ .Values.env.SPRING_KEYCLOAK_URL | quote }}
  SPRING_KAFKA: {{ .Values.env.SPRING_KAFKA }}
