app:
  name: keycloak
  namespace: keycloak
  image: quay.io/keycloak/keycloak:24.0.3
  replicas: 1
  port: 8080
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  KC_PROXY: edge
  KC_HOSTNAME: keycloak.inkcloud.click
  KC_HOSTNAME_URL: https://keycloak.inkcloud.click
  KC_HOSTNAME_STRICT: false
  db:
    KC_DB: mysql
    KC_DB_URL: jdbc:mysql://mysql.inkcloud.svc.cluster.local:3306/keycloak_db
    KC_DB_USERNAME: root
    KC_DB_PASSWORD: 1234
    
service:
  type: ClusterIP
 
ingress:
  enabled: true