apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PoorHotsix/gitops-repo.git 
    targetRevision: HEAD
    path: dev/api-gateway-service
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: inkcloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: 
      - CreateNamespace=true     