apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PoorHotsix/gitops-repo.git  
    targetRevision: HEAD
    path: dev/keycloak
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true