apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  namespace: {{ .Values.app.namespace }}
data:
  SERVER_PORT: {{ .Values.env.SERVER_PORT | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.env.SPRING_PROFILES_ACTIVE | quote }}
  MEMBER_SERVICE_API_URL: {{ .Values.env.MEMBER_SERVICE_API_URL | quote }}
  REVIEW_SERVICE_API_URL: {{ .Values.env.REVIEW_SERVICE_API_URL | quote }}
  STATS_SERVICE_API_URL: {{ .Values.env.STATS_SERVICE_API_URL | quote }}
  ORDER_SERVICE_API_URL: {{ .Values.env.ORDER_SERVICE_API_URL | quote }}
  PAYMENT_SERVICE_API_URL: {{ .Values.env.PAYMENT_SERVICE_API_URL | quote }}
  PRODUCT_SERVICE_API_URL: {{ .Values.env.PRODUCT_SERVICE_API_URL | quote }}
  CART_SERVICE_API_URL: {{ .Values.env.CART_SERVICE_API_URL | quote }}
  BESTSELLERS_SERVICE_API_URL: {{ .Values.env.BESTSELLERS_SERVICE_API_URL | quote }}


