apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.SPRING_PROFILES_ACTIVE | quote }}
            - name: SPRING_KEYCLOAK_URL
              value: {{ .Values.env.SPRING_KEYCLOAK_URL | quote }}
            - name: SERVER_PORT
              value: {{ .Values.env.SERVER_PORT | quote }}
            - name: MEMBER_SERVICE_API_URL
              value: {{ .Values.env.MEMBER_SERVICE_API_URL | quote }}
            - name: REVIEW_SERVICE_API_URL
              value: {{ .Values.env.REVIEW_SERVICE_API_URL | quote }}
            - name: STATS_SERVICE_API_URL
              value: {{ .Values.env.STATS_SERVICE_API_URL | quote }}
            - name: ORDER_SERVICE_API_URL
              value: {{ .Values.env.ORDER_SERVICE_API_URL | quote }}
            - name: PAYMENT_SERVICE_API_URL
              value: {{ .Values.env.PAYMENT_SERVICE_API_URL | quote }}
            - name: PRODUCT_SERVICE_API_URL
              value: {{ .Values.env.PRODUCT_SERVICE_API_URL | quote }}
            - name: CART_SERVICE_API_URL
              value: {{ .Values.env.CART_SERVICE_API_URL | quote }}
            - name: BESTSELLERS_SERVICE_API_URL
              value: {{ .Values.env.BESTSELLERS_SERVICE_API_URL | quote }}