app:
  namespace: review-service
  name: review-service-api
  replicas: 1
  image: '430118853107.dkr.ecr.ap-northeast-2.amazonaws.com/member-service:5368fa3975b3564028f7c628c86283efb5f85e30'
  port: 18000 # 퍄드(컨테이너화된 애플리케이션) 서비스 포트
  resources: {}
  # resources:
  #  requests:
  #    cpu: 300m
  #    memory: 256Mi
  #  limits:
  #    cpu: 300m
  #    memory: 500Mi
podLabels:
  tier: backend
probes:
  readiness: {}
  liveness: {}
# probes:
#  readiness:
#      httpGet:
#      path: /actuator/health/readiness
#      port: 9000
#    initialDelaySeconds: 10
#    periodSeconds: 10
#  liveness:
#    httpGet:
#      path: /actuator/health/liveness
#      port: 9000
#    initialDelaySeconds: 120
#    periodSeconds: 10
service:
  enabled: true
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  className: alb
  host: ""
  path: /
  pathType: Prefix
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://mysql.inkcloud.svc.cluster.local:3306/review_db?serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: root
    password: "1234"
