app:
  namespace: payment-service
  name: payment-service-api
  replicas: 1
  image: '430118853107.dkr.ecr.ap-northeast-2.amazonaws.com/payment-service:latest'
  port: 12000 # 퍄드(컨테이너화된 애플리케이션) 서비스 포트
  resources: {}
podLabels:
  tier: backend
probes:
  readiness: {}
  liveness: {}
service:
  enabled: true
  type: ClusterIP
  port: 80
ingress:
  enabled: false
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://mysql.inkcloud.svc.cluster.local:3306/payment_db?serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: root
    password: "1234"